name: zhttpd

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: windows-x64
            bin_name: zhttpd.exe
          - os: ubuntu-latest
            artifact_name: linux-x64
            bin_name: zhttpd
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build Release
        run: cargo build --release --verbose
      - name: Zip Artifact (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Compress-Archive -Path .\target\release\${{ matrix.bin_name }} -DestinationPath .\${{ matrix.artifact_name }}-bin.zip
      - name: Zip Artifact (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          zip -j ${{ matrix.artifact_name }}-bin.zip ./target/release/${{ matrix.bin_name }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}-bin
          path: ${{ matrix.artifact_name }}-bin.zip

  draft-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: List artifacts
        run: ls -R artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
          files: |
            artifacts/windows-x64-bin/windows-x64-bin.zip
            artifacts/linux-x64-bin/linux-x64-bin.zip
